### PR TITLE
Fix/improve location reporting

### PR DESCRIPTION
**Pull request by blueyed**
- Provide the line number from the current test.
  Fixes https://github.com/fschulze/pytest-pdb/issues/1.
  > Currently in test_foo (path/to/tests/test_bar.py:283) on line 300

- Fix off-by-one error with pytest's item location.
  Fixes https://github.com/fschulze/pytest-pdb/issues/2.

### CODE REVIEW

**Comment by blueyed** [comment]
Not sure about the format.. currently it will allow to quickly go to the test itself (via `file:no`).

We might also want to include the frame number for quick usage with `u` or something else?!

**Comment by fschulze** [comment]
Thanks for the PR! I released 0.2.0.

**Comment by blueyed** [comment]
I have a local fixup:

What do you think?

```diff
diff --git a/pytest_pdb.py b/pytest_pdb.py
index cb013e4..313b39b 100644
--- a/pytest_pdb.py
+++ b/pytest_pdb.py
@@ -25,9 +25,9 @@ def do_whichtest(self, arg):
             return
 
         (item, frame) = test
-        print("Currently in {} ({}:{}) on line {}".format(
-            item.location[2], item.location[0], item.location[1] + 1,
-            frame.f_lineno), file=self.stdout)
+        print("Currently in {} ({}:{})".format(
+            item.location[2], item.location[0], frame.f_lineno),
+              file=self.stdout)
 
 
 def pytest_configure(config):
```

I found it better for copy'n'pasting, and the test's line number is not really useful, is it?

**Comment by fschulze** [comment]
Not sure. I think the test line number may be useful. What copy'n'pasting are you doing with the output?

**Comment by blueyed** [comment]
> What copy'n'pasting are you doing with the output?

Double-click in the terminal to get it into the PRIMARY clipboard, and then edit the file.
I have Vim configured to handle 'foo:23' - opening foo at line 23.  This is the format often used in stacktraces and the like.

I would argue that it's easy to go from inside of the test (where you actually got into the debugger from) to the top of the test, and that's it not so common to go to the beginning of the test directly.
We could have something like "defined on line X", but then it's more information to be read that is not really useful IMHO.

**Pull request merged**
